### PR TITLE
Add support for partial compound index queries (closes #272)

### LINKED ISSUE #272: Support for range query using compound index?
I have a `user_items` table with a compound index on `[:user_id, :item_id]`.  I'm trying to do a range query, but I can't get NoBrainer to use the index:

    UserItem.where(:user_id => '9O6ZCaYTjj8Mgt', :item_id.gt => '9UX88eKUTrlbRH').to_rql

    r.table("user_items").order_by({"index" => r.asc(:id)}).filter {|var_2|
      var_2[:user_id].eq("9O6ZCaYTjj8Mgt").and(
        var_2[:item_id].gt("9UX88eKUTrlbRH")
      )
    }

... when what I want is ...

    r.table("user_items").between(
      [ "9O6ZCaYTjj8Mgt", "9UX88eKUTrlbRH" ],
      [ "9O6ZCaYTjj8Mgt", r.maxval ], 
      { "leftBound" => "open", "index" => "user_id_item_id" }
    ).order_by({ "index" => r.asc(:id) })

It seems like https://github.com/nviennot/nobrainer/blob/master/lib/no_brainer/criteria/where.rb#L393 prevents compound indexes from being used unless the query has equality arguments for all fields in the index.  I can see why you might want to avoid supporting partial indexes in general, as the logic to select the best of several different indexes could get insanely complex, but it doesn't seem like much of a stretch to use compound indexes when one of the fields uses an inequality.

In any event, can you suggest a workaround to support this case?  Thanks ...

### PR DESCRIPTION
**Pull request by CodeMonkeySteve**

### CODE REVIEW

**Comment by zedtux** [comment]
Kind a strange that Travis has not run ...

**Comment by CodeMonkeySteve** [comment]
Refactored to make compound-partial the strategy of last resort (to preserve backward compatibility)

**Comment by zedtux** [comment]
Could you please rebase your PR so that this PR is up-to-date and it will trigger the build now the CI is working again?

**Comment by zedtux** [comment]
I've finally migrated the project to Github Actions and the build is green on `master`.

I've already asked you to rebase your branch, and I'm sorry to ask you this again, but can you please rebase again your branch please ?

**Comment by CodeMonkeySteve** [comment]
Rebased, with a small fix for Ruby2.2/Rails4.

**Comment by zedtux** [comment]
Sorry for the bad GH Actions configuration. It's now fixed (tested with my old fork of this project). Can you please rebase again ? It should trigger the build.

**Comment by zedtux** [comment]
LGTM thank you ! I think an update of the "Indexes" documentation page would be great in order to explain this index support extension. Could be just a sentence or more if you feel inspired :wink:

**Comment by CodeMonkeySteve** [comment]
Happy to add docs, now that I'm a reluctant expert in partial indexes.  Is this the page to add that? https://github.com/NoBrainerORM/nobrainer.io/blob/master/docs/indexes.md

**Comment by zedtux** [comment]
Yes, that's the right page.

**Pull request merged**
